### ISSUE TITLE
Logo offer for ImagePicker

### ISSUE THREAD

**Issue by familqasimov** [CaoyangLee/ImagePicker#3]
Hi sir. I'm graphic designer. I have studied your work and I think a new design will make you more visible. I would like to offer logo. I can give you all the formats of the design free. If you want I send you PR or a change please specify.

![untitled-1](https://user-images.githubusercontent.com/36432269/40131822-0d17c5fe-594c-11e8-8b25-61c3693d820b.png)

Best Regards
Famil Qasimov

**Comment by CaoyangLee** [comment]
thanks you.
